export const { 
  REACT_APP_APP_URL: BASE_URL,
  REACT_APP_FIREBASE_API_KEY: FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN: FIREBASE_AUTH_DOMAIN,
  REACT_APP_PROJECT_ID: PROJECT_ID
} = process.env;